[package]
name = "dependabot" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["support@dependabot.com"]

[dependencies]
time = "=0.3.0-alpha-1"
regex = ">=1.6.0, <1.7.0"
itoa = { git = "https://github.com/dtolnay/itoa.git", tag = "1.0.5" }
